apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "pdthole@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "dqlu yhiq bjdf noqg"
type: Opaque

# Passw0rd@1234